# Generated by Django 5.2.4 on 2025-08-01 00:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_creation_enabled', models.BooleanField(default=True)),
                ('card_approval_enabled', models.BooleanField(default=True)),
                ('card_rejection_enabled', models.BooleanField(default=True)),
                ('card_activation_enabled', models.BooleanField(default=True)),
                ('card_deactivation_enabled', models.BooleanField(default=True)),
                ('document_upload_enabled', models.BooleanField(default=True)),
                ('new_request_enabled', models.BooleanField(default=True)),
                ('system_enabled', models.BooleanField(default=True)),
                ('security_enabled', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=False)),
                ('browser_notifications', models.BooleanField(default=True)),
                ('sound_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('info', 'Information'), ('warning', 'Warning'), ('alert', 'Alert')], max_length=20)),
                ('category', models.CharField(choices=[('card_creation', 'Card Creation'), ('card_approval', 'Card Approval'), ('card_rejection', 'Card Rejection'), ('card_activation', 'Card Activation'), ('card_deactivation', 'Card Deactivation'), ('document_upload', 'Document Upload'), ('new_request', 'New Request'), ('request_approved', 'Request Approved'), ('request_rejected', 'Request Rejected'), ('system', 'System'), ('security', 'Security')], max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('is_important', models.BooleanField(default=False)),
                ('related_card_id', models.IntegerField(blank=True, null=True)),
                ('related_request_id', models.IntegerField(blank=True, null=True)),
                ('action_url', models.URLField(blank=True, help_text="URL d'action pour la notification", null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx'), models.Index(fields=['category'], name='notificatio_categor_fd561f_idx')],
            },
        ),
    ]
