# Generated by Django 5.2.4 on 2025-07-31 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarteVirtuelle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numeroCart', models.CharField(blank=True, max_length=16, unique=True)),
                ('cvv2', models.CharField(blank=True, max_length=3)),
                ('dateExpiration', models.DateField()),
                ('dateCreation', models.DateTimeField(auto_now_add=True)),
                ('card_type', models.CharField(choices=[('shopping', 'Shopping Card'), ('travel', 'Travel Card'), ('business', 'Business Card'), ('personal', 'Personal Card')], default='personal', max_length=20)),
                ('card_name', models.CharField(help_text='Custom name for the card', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('blocked', 'Blocked'), ('expired', 'Expired'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartes_virtuelles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carte Virtuelle',
                'verbose_name_plural': 'Cartes Virtuelles',
                'ordering': ['-dateCreation'],
            },
        ),
        migrations.CreateModel(
            name='CardRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('shopping', 'Shopping Card'), ('travel', 'Travel Card'), ('business', 'Business Card'), ('personal', 'Personal Card')], max_length=20)),
                ('card_name', models.CharField(max_length=100)),
                ('requested_limit', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10)),
                ('age_verified', models.BooleanField(default=False)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('emergency_contact', models.CharField(blank=True, max_length=20)),
                ('profession', models.CharField(blank=True, max_length=100)),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('identity_document', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('income_proof', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('reason', models.TextField(help_text='Reason for requesting this card')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_comments', models.TextField(blank=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('approved_card', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cards.cartevirtuelle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
